import time 
now=time.ctime()
qna = {
    "hi":"hello",
    "what is your name":"My name is Chatbot",
    "how are you":"I am Fine",
    "what is the time now":f"The time is:-  {now}",
    "how was your day":"My day was good,thank you for asking!",
    "what is your name": "I am a chatbot created by OpenAI. You can call me ChatGPT.",
    "how are you": "As an AI, I don't have feelings, but I'm here and ready to assist you!",
    "what can you do": "I can help answer questions, provide information, or just have a conversation with you.",
    "who created you": "I was created by Payal soni a very professinol and experienced Programmer, she is very polite and helpfull and dedicated to get placement in Palo alto",
    "what is your name": "My name is payals AI",
    "how are you": "As an AI, I don't have feelings, but I'm here and ready to assist you!",
    "what can you do": "I can help answer questions, provide information, or just have a conversation with you.",
    
    "what is the meaning of life": "The meaning of life can be different for everyone. Some find meaning in relationships, others in accomplishments or personal fulfillment.",
    "can you tell a joke": "Sure! Why don't scientists trust atoms? Because they make up everything!",
    "tell me something interesting": "Did you know that the shortest war in history lasted only 38 minutes between Britain and Zanzibar in 1896?",
    "what is the capital of france": "The capital of France is Paris.",
    "how do you spell mississippi": "M-I-S-S-I-S-S-I-P-P-I.",
    "what is the tallest mountain in the world": "Mount Everest is the tallest mountain in the world.",
    "what is the population of the united states": "The population of the United States is approximately 331 million people.",
    "what is the square root of 144": "The square root of 144 is 12.",
    "what is the speed of light": "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
    "how many continents are there": "There are seven continents: Africa, Antarctica, Asia, Europe, North America, Australia (Oceania), and South America.",
    "what is the largest ocean": "The Pacific Ocean is the largest ocean in the world.",
    "what is the capital of japan": "The capital of Japan is Tokyo.",
    "how many teaspoons are in a tablespoon": "There are three teaspoons in a tablespoon.",
    "what is the chemical symbol for water": "The chemical symbol for water is H2O.",
    "who wrote romeo and juliet": "William Shakespeare wrote 'Romeo and Juliet'.",
    "what is the currency of japan": "The currency of Japan is the Japanese yen.",
    "how many sides does a triangle have": "A triangle has three sides.",
    "what is the largest desert in the world": "The largest desert in the world is the Sahara Desert.",
    "what year did the titanic sink": "The Titanic sank in 1912.",
    "what is the boiling point of water": "The boiling point of water is 100 degrees Celsius or 212 degrees Fahrenheit at sea level.",
    "what is the capital of australia": "The capital of Australia is Canberra.",
    "what is the largest animal in the world": "The blue whale is the largest animal in the world.",
    "what is the capital of spain": "The capital of Spain is Madrid.",
    "what is the chemical symbol for gold": "The chemical symbol for gold is Au.",
    "who painted the mona lisa": "Leonardo da Vinci painted the Mona Lisa.",
    "what is the national animal of china": "The national animal of China is the giant panda.",
    "how many feet are in a mile": "There are 5,280 feet in a mile.",
    "what is the largest city in the world": "The largest city in the world by population is Tokyo, Japan.",
    "what is the capital of italy": "The capital of Italy is Rome.",
    "what is the chemical symbol for oxygen": "The chemical symbol for oxygen is O.",
    "who wrote to kill a mockingbird": "Harper Lee wrote 'To Kill a Mockingbird'.",
    "what is the currency of india": "The currency of India is the Indian Rupee.",
    "what is the largest planet in our solar system": "Jupiter is the largest planet in our solar system.",
    "what is the capital of china": "The capital of China is Beijing.",
    "what is the chemical symbol for carbon": "The chemical symbol for carbon is C.",
    "who painted the starry night": "Vincent van Gogh painted the Starry Night.",
    "what is the national animal of india": "The national animal of India is the Bengal tiger.",
    "how many bones are in the human body": "The adult human body has 206 bones.",
    "what is the capital of brazil": "The capital of Brazil is Brasília.",
    "what is the chemical symbol for silver": "The chemical symbol for silver is Ag.",
    "who wrote 1984": "George Orwell wrote '1984'.",
    "what is the currency of russia": "The currency of Russia is the Russian Ruble.",
    "what is the smallest country in the world": "The smallest country in the world is Vatican City.",
    "what is the capital of canada": "The capital of Canada is Ottawa.",
    "what is the chemical symbol for sodium": "The chemical symbol for sodium is Na.",
    "who painted the sistine chapel ceiling": "Michelangelo painted the Sistine Chapel ceiling.",
    "what is the national animal of the united states": "The national animal of the United States is the bald eagle.",
    "how many planets are in our solar system": "There are eight planets in our solar system.",
    "what is the capital of south africa": "The capital of South Africa is Pretoria (administrative), Cape Town (legislative), and Bloemfontein (judicial).",
    "what is the chemical symbol for iron": "The chemical symbol for iron is Fe.",
    "who wrote pride and prejudice": "Jane Austen wrote 'Pride and Prejudice'.",
    "what is the currency of china": "The currency of China is the Chinese Yuan (Renminbi).",
    "what is the deepest ocean trench": "The Mariana Trench is the deepest ocean trench.",
    "what is the capital of south korea": "The capital of South Korea is Seoul.",
    "what is the chemical symbol for nitrogen": "The chemical symbol for nitrogen is N.",
    "who painted the last supper": "Leonardo da Vinci painted the Last Supper.",
    "what is the national animal of australia": "The national animal of Australia is the red kangaroo.",
    "how many chambers does the human heart have": "The human heart has four chambers.",
    "what is the capital of russia": "The capital of Russia is Moscow.",
    "what is the chemical symbol for helium": "The chemical symbol for helium is He.",
    "who wrote the great gatsby": "F. Scott Fitzgerald wrote 'The Great Gatsby'.",
    "what is the currency of japan": "The currency of Japan is the Japanese yen.",
    "what is the highest mountain in africa": "Mount Kilimanjaro is the highest mountain in Africa.",
    "what is the capital of mexico": "The capital of Mexico is Mexico City.",
    "what are the colors of the indian flag": "The Indian flag consists of three colors: saffron, white, and green, with a navy blue Ashoka Chakra in the middle.",
    "what is the national flower of india": "The national flower of India is the lotus.",
    "what is the national bird of india": "The national bird of India is the Indian peacock.",
    "what is the national tree of india": "The national tree of India is the banyan tree.",
    "what is the national fruit of india": "The national fruit of India is the mango.",
    "what is the national animal of india": "The national animal of India is the Bengal tiger.",
    "what is the national song of india": "The national song of India is 'Vande Mataram'.",
    "what is the national anthem of india": "The national anthem of India is 'Jana Gana Mana'.",
    "what is the capital of india": "The capital of India is New Delhi.",
    "what is the largest city in india": "The largest city in India is Mumbai (formerly known as Bombay).",
    "what are the major languages spoken in india": "The major languages spoken in India include Hindi, Bengali, Telugu, Marathi, Tamil, Urdu, Gujarati, Kannada, Punjabi, and Malayalam.",
    "what is the currency of india": "The currency of India is the Indian Rupee (INR).",
    "what is the population of india": "As of the latest data, the population of India is over 1.3 billion people, making it the second most populous country in the world.",
    "what is the highest mountain peak in india": "The highest mountain peak in India is Kangchenjunga, which stands at 8,586 meters (28,169 feet) above sea level.",
    "what is the national sport of india": "The national sport of India is field hockey.",
    "what is the largest state in india by area": "The largest state in India by area is Rajasthan.",
    "what is the smallest state in india by area": "The smallest state in India by area is Goa.",
    "what is the longest river in india": "The longest river in India is the Ganges River.",
    "what is the holiest river in india": "The holiest river in India is the Ganges River.",
    "what is the largest state in india by population": "The largest state in India by population is Uttar Pradesh.",
    "what is the smallest state in india by population": "The smallest state in India by population is Sikkim.",
    "what is the literacy rate in india": "As of the latest data, the literacy rate in India is around 74%.",
    "what is the oldest city in india": "Varanasi, also known as Kashi or Banaras, is considered one of the oldest continuously inhabited cities in the world.",
    "what is the largest desert in india": "The Thar Desert, also known as the Great Indian Desert, is the largest desert in India.",
    "what is the largest lake in india": "The largest lake in India is Wular Lake in Jammu and Kashmir.",
    "what is the most famous landmark in india": "The Taj Mahal in Agra is one of the most famous landmarks in India.",
    "what is the highest waterfall in india": "The highest waterfall in India is Jog Falls in Karnataka.",
    "what is the largest national park in india": "The largest national park in India is Hemis National Park in Ladakh, Jammu, and Kashmir.",
    "what is the largest temple in india": "The largest temple in India is the Srirangam Temple in Tamil Nadu.",
    "what is the largest mosque in india": "The largest mosque in India is the Jama Masjid in Delhi.",
    "what is the largest church in india": "The largest church in India is the Basilica of Our Lady of Good Health in Velankanni, Tamil Nadu.",
    "what is the largest stadium in india": "The largest stadium in India is the Salt Lake Stadium in Kolkata.",
    "what is the largest university in india": "The largest university in India is Indira Gandhi National Open University (IGNOU) in New Delhi.",
    "what is the largest film industry in india": "The largest film industry in India is Bollywood, based in Mumbai.",
    "what is the largest state-owned bank in india": "The largest state-owned bank in India is the State Bank of India (SBI).",
    "what is the largest private bank in india": "The largest private bank in India is HDFC Bank.",
    "what is the largest mountain range in india": "The largest mountain range in India is the Himalayas.",
    "what is the largest plateau in india": "The largest plateau in India is the Deccan Plateau.",
    "what is the largest dam in india": "The largest dam in India is the Tehri Dam in Uttarakhand.",
    "what is the largest fort in india": "The largest fort in India is the Chittorgarh Fort in Rajasthan.",
    "what is the largest cave in india": "The largest cave in India is the Belum Caves in Andhra Pradesh.",
    "what is the largest island in india": "The largest island in India is Majuli Island in Assam.",
    "what is the largest museum in india": "The largest museum in India is the Indian Museum in Kolkata.",
    "what is the largest zoo in india": "The largest zoo in India is the Arignar Anna Zoological Park in Chennai.",
    "what is the largest library in india": "The largest library in India is the National Library of India in Kolkata.",
    "what is the largest IT company in india": "The largest IT company in India is Tata Consultancy Services (TCS).",
    "what is the largest software company in india": "The largest software company in India is Infosys.",
    "what is the largest IT park in india": "The largest IT park in India is the Rajiv Gandhi IT Park in Chandigarh.",
    "what is the largest science center in india": "The largest science center in India is the Visvesvaraya Industrial and Technological Museum in Bangalore.",
    "what is the largest shopping mall in india": "The largest shopping mall in India is the LuLu International Shopping Mall in Kochi, Kerala.",
    "what is the largest railway station in india": "The largest railway station in India is Howrah Junction in Kolkata.",
    "what is the largest airport in india": "The largest airport in India is the Indira Gandhi International Airport in Delhi.",
    "what is the largest port in india": "The largest port in India is the Jawaharlal Nehru Port in Maharashtra.",
    "what is the largest island in india": "The largest island in India is Andaman Island.",
    "what is the largest forest in india": "The largest forest in India is Sundarbans Forest in West Bengal."


    
}


while True:
    qs = input("Enter query : ")
    if (qs=="quit") or qs == "exit" :
        break
    else:
        if qs in qna:
            print(qna[qs])
        else:
            print("OOPS...Answer not found")